<?php

/**
 * Implements hook_theme().
 */
function helpful_theme() {
    return [
        'helpful_ticket_block' => [
            'variables' => [
                'data' => [],
            ],
            'template' => 'block--helpful-ticket-block',
        ],
        'page_ticket' => [
            'variables' => [
                'data' => [],
            ],
            'templates' => 'page_ticket',
        ],
    ];
}